/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulator;

import java.awt.Color;

/**
 *
 * @author 62877
 */
public class KalkulatorFrame extends javax.swing.JFrame {
    private boolean lanjutAngka;
    private Kalkulator kal;
    

    /**
     * Creates new form FrameKalkulator
     */
    public KalkulatorFrame() {
        lanjutAngka= true;
        kal = new Kalkulator();
        getContentPane().setBackground(new Color(18, 38, 32));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        txtTampilan = new javax.swing.JTextField();
        btnDua = new javax.swing.JButton();
        btnSatu = new javax.swing.JButton();
        btnTiga = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnLima = new javax.swing.JButton();
        btnEmpat = new javax.swing.JButton();
        btnEnam = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnmin = new javax.swing.JButton();
        btnbagi = new javax.swing.JButton();
        btnkali = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(143, 59, 59));

        txtTampilan.setBackground(new java.awt.Color(18, 38, 32));
        txtTampilan.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        txtTampilan.setForeground(new java.awt.Color(255, 255, 255));
        txtTampilan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTampilan.setText("0");
        txtTampilan.setBorder(null);

        btnDua.setBackground(new java.awt.Color(182, 141, 64));
        btnDua.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        btnDua.setForeground(new java.awt.Color(255, 255, 255));
        btnDua.setText("2");
        btnDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuaActionPerformed(evt);
            }
        });

        btnSatu.setBackground(new java.awt.Color(182, 141, 64));
        btnSatu.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        btnSatu.setForeground(new java.awt.Color(255, 255, 255));
        btnSatu.setText("1");
        btnSatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatuActionPerformed(evt);
            }
        });

        btnTiga.setBackground(new java.awt.Color(182, 141, 64));
        btnTiga.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        btnTiga.setForeground(new java.awt.Color(255, 255, 255));
        btnTiga.setText("3");
        btnTiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTigaActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(244, 235, 208));
        jButton5.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(18, 38, 32));
        jButton5.setText("=");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnLima.setBackground(new java.awt.Color(182, 141, 64));
        btnLima.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        btnLima.setForeground(new java.awt.Color(255, 255, 255));
        btnLima.setText("5");
        btnLima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimaActionPerformed(evt);
            }
        });

        btnEmpat.setBackground(new java.awt.Color(182, 141, 64));
        btnEmpat.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        btnEmpat.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpat.setText("4");
        btnEmpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpatActionPerformed(evt);
            }
        });

        btnEnam.setBackground(new java.awt.Color(182, 141, 64));
        btnEnam.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        btnEnam.setForeground(new java.awt.Color(255, 255, 255));
        btnEnam.setText("6");
        btnEnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnamActionPerformed(evt);
            }
        });

        btnPlus.setBackground(new java.awt.Color(214, 173, 96));
        btnPlus.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        btnPlus.setForeground(new java.awt.Color(255, 255, 255));
        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(182, 141, 64));
        btn8.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(182, 141, 64));
        btn7.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(182, 141, 64));
        btn9.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnmin.setBackground(new java.awt.Color(214, 173, 96));
        btnmin.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        btnmin.setForeground(new java.awt.Color(255, 255, 255));
        btnmin.setText("-");
        btnmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminActionPerformed(evt);
            }
        });

        btnbagi.setBackground(new java.awt.Color(214, 173, 96));
        btnbagi.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        btnbagi.setForeground(new java.awt.Color(255, 255, 255));
        btnbagi.setText("/");
        btnbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbagiActionPerformed(evt);
            }
        });

        btnkali.setBackground(new java.awt.Color(214, 173, 96));
        btnkali.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        btnkali.setForeground(new java.awt.Color(255, 255, 255));
        btnkali.setText("x");
        btnkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaliActionPerformed(evt);
            }
        });

        jButtonDot.setBackground(new java.awt.Color(244, 235, 208));
        jButtonDot.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jButtonDot.setForeground(new java.awt.Color(18, 38, 32));
        jButtonDot.setText(".");
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });

        jButton0.setBackground(new java.awt.Color(182, 141, 64));
        jButton0.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jButton0.setForeground(new java.awt.Color(255, 255, 255));
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEmpat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(btnEnam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnmin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnkali, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(txtTampilan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnSatu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLima, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTiga, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addComponent(btn9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn7, btn8, btnDua, btnEmpat, btnLima, btnPlus, btnSatu, btnTiga, btnbagi, btnkali, btnmin, jButton0, jButtonDot});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(txtTampilan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSatu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDua, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTiga, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmpat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLima, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnam, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnkali, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn7, btn8, btn9, btnDua, btnEmpat, btnEnam, btnLima, btnPlus, btnSatu, btnTiga, btnbagi, btnkali, btnmin, jButton0, jButton5, jButtonDot});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTigaActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(txtTampilan.getText());
        if (lanjutAngka == true){
        long angkaBaru = angka * 10 +3;
        txtTampilan.setText(""+angkaBaru);
    }                                       
        else {
            txtTampilan.setText("3");
            lanjutAngka= true;
        }
    }//GEN-LAST:event_btnTigaActionPerformed

    private void btnSatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatuActionPerformed
        long angka = Long.parseLong(txtTampilan.getText());
        if (lanjutAngka == true){
        long angkaBaru = angka * 10 +1;
        txtTampilan.setText(""+angkaBaru);
    }//GEN-LAST:event_btnSatuActionPerformed
        else {
            txtTampilan.setText("1");
            lanjutAngka= true;
        }
    }
    
    private void btnEmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpatActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(txtTampilan.getText());
        if (lanjutAngka == true){
        long angkaBaru = angka * 10 +4;
        txtTampilan.setText(""+angkaBaru);
    }                                       
        else {
            txtTampilan.setText("4");
            lanjutAngka= true;
        }
    }//GEN-LAST:event_btnEmpatActionPerformed

    private void btnEnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnamActionPerformed
        // TODO add your handling code here:
    long angka = Long.parseLong(txtTampilan.getText());
        if (lanjutAngka == true){
        long angkaBaru = angka * 10 +6;
        txtTampilan.setText(""+angkaBaru);
    }                                       
        else {
            txtTampilan.setText("6");
            lanjutAngka= true;
        }
    }//GEN-LAST:event_btnEnamActionPerformed

    private void btnDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuaActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(txtTampilan.getText());
        if (lanjutAngka == true){
        long angkaBaru = angka * 10 +2;
        txtTampilan.setText(""+angkaBaru);
    }                                       
        else {
            txtTampilan.setText("2");
            lanjutAngka= true;
        }
    }//GEN-LAST:event_btnDuaActionPerformed

    private void btnLimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimaActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(txtTampilan.getText());
        if (lanjutAngka == true){
        long angkaBaru = angka * 10 +5;
        txtTampilan.setText(""+angkaBaru);
    }                                       
        else {
            txtTampilan.setText("5");
            lanjutAngka= true;
        }
    }//GEN-LAST:event_btnLimaActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        // TODO add your handling code here:
        lanjutAngka = false;
        long angka= Long.parseLong(txtTampilan.getText());
        
        kal.tambahkan(angka);
    }//GEN-LAST:event_btnPlusActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(txtTampilan.getText());
        
        long hasil = kal.eksekusiOperasi(angka);
        txtTampilan.setText(""+hasil);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
            long angka = Long.parseLong(txtTampilan.getText());
        if (lanjutAngka == true){
        long angkaBaru = angka * 10 +8;
        txtTampilan.setText(""+angkaBaru);
    }                                       
        else {
            txtTampilan.setText("8");
            lanjutAngka= true;
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
            long angka = Long.parseLong(txtTampilan.getText());
        if (lanjutAngka == true){
        long angkaBaru = angka * 10 +7;
        txtTampilan.setText(""+angkaBaru);
    }                                       
        else {
            txtTampilan.setText("7");
            lanjutAngka= true;
        }
        
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
            long angka = Long.parseLong(txtTampilan.getText());
        if (lanjutAngka == true){
        long angkaBaru = angka * 10 +9;
        txtTampilan.setText(""+angkaBaru);
    }                                       
        else {
            txtTampilan.setText("9");
            lanjutAngka= true;
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminActionPerformed
        // TODO add your handling code here:
         lanjutAngka = false;
        long angka= Long.parseLong(txtTampilan.getText());
        
        kal.kurangkan(angka);
    }//GEN-LAST:event_btnminActionPerformed

    private void btnbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbagiActionPerformed
        // TODO add your handling code here:
        lanjutAngka = false;
        long angka= Long.parseLong(txtTampilan.getText());


    }//GEN-LAST:event_btnbagiActionPerformed

    private void btnkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkaliActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
          long angka = Long.parseLong(txtTampilan.getText());
        if (lanjutAngka == true){
        long angkaBaru = angka * 10 +0;
        txtTampilan.setText(""+angkaBaru);
    }                                       
        else {
            txtTampilan.setText("0");
            lanjutAngka= true;
        }
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnDua;
    private javax.swing.JButton btnEmpat;
    private javax.swing.JButton btnEnam;
    private javax.swing.JButton btnLima;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnSatu;
    private javax.swing.JButton btnTiga;
    private javax.swing.JButton btnbagi;
    private javax.swing.JButton btnkali;
    private javax.swing.JButton btnmin;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JTextField txtTampilan;
    // End of variables declaration//GEN-END:variables
}
